"""Configuration module for pipeline settings."""

import os

NOT_SET = "not_set"

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", NOT_SET)
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", NOT_SET)
AWS_DEFAULT_REGION = os.getenv("AWS_DEFAULT_REGION", NOT_SET)
AWS_S3_BUCKET_NAME = os.getenv("S3_BUCKET", NOT_SET)
SP500_URL = os.getenv("SP500_URL", NOT_SET)
AWS_S3_GOLD_DIR_PREFIX = os.getenv("AWS_S3_GOLD_DIR_PREFIX", "gold")
AWS_S3_GOLD_PREFIX_SP500_DAILY_PRICES = os.getenv(
    "AWS_S3_GOLD_PREFIX_SP500_DAILY_PRICES", "sp500_daily_prices"
)
AWS_S3_GOLD_DAILY_PRICES = os.getenv("AWS_S3_GOLD_DAILY_PRICES_OUTPUT", "sp500_gold")


class Config:
    """Configuration class for streamlit settings."""

    AWS_ACCESS_KEY_ID = AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION = AWS_DEFAULT_REGION

    AWS_S3_BUCKET_NAME = AWS_S3_BUCKET_NAME
    AWS_S3_FILE_KEY_GOLD = (
        f"{AWS_S3_GOLD_DIR_PREFIX}/{AWS_S3_GOLD_PREFIX_SP500_DAILY_PRICES}/"
    )
    AWS_GOLD_DAILY_SP500_OUTPUT = AWS_S3_GOLD_DAILY_PRICES
